LITReview_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf.urls.static import static
from reviews import views

import reviews.views
import authentication.views

urlpatterns = [
    url(r'^$', reviews.views.home, name='home'),
    url(r'^login/', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True),
        name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', reviews.views.home, name='home'),
    url(r'^signup/$', authentication.views.signup_page, name='signup'),
    url(r'^view_follows$', reviews.views.view_follows, name='view_follows'),
    url(r'^reviews/ticket_create$', reviews.views.ticket_upload, name='ticket_create'),
    url(r'^reviews/ticket_and_review_create$', reviews.views.review_and_ticket_upload, name='review_and_ticket_create'),
    url(r'^reviews/my_posts$', reviews.views.my_posts, name='my_posts'),
    path('delete_follows/<int:follower_id>', reviews.views.delete_follows, name='delete_follows'),
    path('add_follow/', reviews.views.add_follow, name='add_follow'),
    path('reviews/<int:ticket_id>', reviews.views.view_ticket, name='view_ticket'),
    path('reviews/<int:ticket_id>/edit', reviews.views.edit_ticket, name='edit_ticket'),
    path('reviews/<int:ticket_id>/delete_ticket', reviews.views.delete_ticket, name='delete_ticket'),
    path('reviews/<int:ticket_id>/review_create', reviews.views.review_upload, name='review_create'),
    path('reviews/<int:ticket_id>/<int:review_id>', reviews.views.view_review, name='view_review'),
    path('reviews/<int:ticket_id>/<int:review_id>/edit', reviews.views.edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete_review', reviews.views.delete_review, name='delete_review'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.conf.urls import url

from . import views # import views so we can use them in urls.
import reviews.views

urlpatterns = [
    # url(r'^$', views.index), # "/store" will call the method "index" in "views.py"
    # url(r'^$', views.listing, name='listing'),
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^search/$', views.search, name='search'),
]

reviews/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models

from PIL import Image


class Ticket(models.Model):
    IMAGE_MAX_SIZE = (900, 900)
    
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def resize_image(self):
        print("self")
        print(self)
        print(self.image)
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, unique=True, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ['user', 'followed_user']

reviews/forms.py
from django import forms
from django.forms.widgets import TextInput

from . import models


class TicketForm(forms.ModelForm):
    edit_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = models.Ticket
        fields = ['title', 'description', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class' : "form-control"}),
            'description': forms.TextInput(attrs={'class' : "form-control"}),
        }


class DeleteTicketForm(forms.Form):
    delete_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class ReviewForm(forms.ModelForm):
    edit_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    
    class Meta:
        model = models.Review
        fields = ['headline', 'rating', 'body']
        widgets = {
            'headline': forms.TextInput(attrs={'class' : "form-control"}),
            'rating': forms.RadioSelect(
                choices=[
                    (0, '0'),
                    (1, '1'),
                    (2, '2'),
                    (3, '3'),
                    (4, '4'),
                    (5, '5'),
                ],
                attrs={"required": True}
                ),
            'body': forms.TextInput(attrs={'class' : "form-control"}),
        }


class DeleteReviewForm(forms.Form):
    delete_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class DeleteFollowedUserForm(forms.Form):
    delete_follow = forms.BooleanField(widget=forms.HiddenInput, initial=True)

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.paginator import Paginator
from itertools import chain
from django.template import loader, RequestContext
from collections import OrderedDict

from . import forms, models
from authentication.models import User

@login_required
def ticket_upload(request):
    ticket_form = forms.TicketForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if any([ticket_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('home')

    context = {
        'ticket_form': ticket_form,
    }
    return render(request, 'reviews/create_ticket.html', context=context)

@login_required
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    edit_ticket = forms.TicketForm(instance=ticket)
    delete_ticket = forms.DeleteTicketForm()
    if request.method == 'POST':
        edit_ticket = forms.TicketForm(request.POST, request.FILES, instance=ticket)
        if edit_ticket.is_valid():
            edit_ticket.save()
            return redirect('home')
        if 'delete_ticket' in request.POST:
            delete_ticket = forms.DeleteTicketForm(request.POST)
            if delete_ticket.is_valid():
                ticket.delete()
                return redirect('home')
    context = {
        'edit_ticket': edit_ticket,
        'delete_ticket': delete_ticket,
    }
    return render(request, 'reviews/edit_ticket.html', context=context)

@login_required
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    if request.method == 'POST':
        ticket.delete()
    return redirect('my_posts')


@login_required
def edit_review(request, ticket_id, review_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review = get_object_or_404(models.Review, id=review_id)
    edit_review = forms.ReviewForm(instance=review)
    delete_review = forms.DeleteReviewForm()
    if request.user == review.user:
        if request.method == 'POST':
            edit_review = forms.ReviewForm(request.POST, instance=review)
            if edit_review.is_valid():
                edit_review.save()
                return redirect('home')
            if 'delete_review' in request.POST:
                delete_review = forms.DeleteReviewForm(request.POST)
                if delete_review.is_valid():
                    review.delete()
                    return redirect('home')
        else:
            context = {
                'ticket': ticket,
                'edit_review': edit_review,
                'delete_review': delete_review,
            }
            return render(request, 'reviews/edit_review.html', context=context)
    context = {
        'ticket': ticket,
        'review': review,
    }
    return render(request, 'reviews/view_review.html', context=context)

@login_required
def delete_review(request, review_id):
    review = get_object_or_404(models.Review, id=review_id)
    if request.user == review.user:
        if request.method == 'POST':
            review.delete()
    return redirect('my_posts')


@login_required
def review_upload(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        review_form = forms.ReviewForm(request.POST)
        if any([review_form.is_valid()]):
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect('home')
    context = {
        'ticket': ticket,
        'review_form': review_form,
    }
    return render(request, 'reviews/create_review.html', context=context)

@login_required
def view_review(request, ticket_id, review_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review = get_object_or_404(models.Review, id=review_id)
    context = {
        'ticket': ticket,
        'review': review,
        'rating': review.rating,
    }
    return render(request, 'reviews/view_review.html', context=context)

@login_required
def view_follows(request):
    # followers = get_object_or_404(models.UserFollows, id=request.user.id)
    followers = models.UserFollows.objects.all()
    context = {
        'followers': followers,
    }
    return render(request, 'reviews/view_follows.html', context=context)

@login_required
def add_follow(request):
    if request.method == 'POST':
        try:
            form = request.POST
            user1 = get_object_or_404(User, username=request.user.username)
            user2 = get_object_or_404(User, username=form["follow_user"])
            if user1 == user2:
                return redirect(view_follows)
            models.UserFollows.objects.create(user=user1,
                                    followed_user=user2)
        except:
            return redirect(view_follows)
    return redirect(view_follows)

@login_required
def delete_follows(request, follower_id):
    followed = get_object_or_404(models.UserFollows, id=follower_id)
    followed.delete()
    return redirect(view_follows)

@login_required
def review_and_ticket_upload(request):
    review_form = forms.ReviewForm()
    ticket_form = forms.TicketForm()
    if request.method == 'POST':
        review_form = forms.ReviewForm(request.POST)
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if all([review_form.is_valid(), ticket_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect('home')
    context = {
        'ticket_form': ticket_form,
        'review_form': review_form,
    }
    return render(request, 'reviews/create_reviews_ticket.html', context=context)

@login_required
def home(request):
    follow = models.UserFollows.objects.filter(user=request.user.id)
    followers = []
    all_tickets = []
    all_reviews = []
    all_reviews_from_user = []
    followers.append(request.user)
    for follower in follow:
        followers.append(follower.followed_user)
    for user_data in followers:
        reviews_from_user = models.Review.objects.filter(ticket__user=user_data)
        reviews = models.Review.objects.filter(user=user_data)
        tickets = models.Ticket.objects.filter(user=user_data)
        if tickets.exists():
            all_tickets = chain(all_tickets, tickets)
        if reviews.exists():
            all_reviews = chain(all_reviews, reviews)
        if reviews_from_user.exists():
            all_reviews_from_user = chain(all_reviews_from_user, reviews_from_user)

    tickets_and_reviews = sorted(
        chain(all_tickets, all_reviews, all_reviews_from_user),
        key=lambda instance: instance.time_created,
        reverse=True
    )

    no_doublons = OrderedDict((x, True) for x in tickets_and_reviews).keys()
    tickets_and_reviews.clear()
    for item in no_doublons:
        tickets_and_reviews.append(item)

    paginator = Paginator(tickets_and_reviews, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'all_tickets': tickets,
        'page_obj': page_obj,
    }

    return render(request, 'reviews/home.html', context=context)

@login_required
def my_posts(request):
    tickets = models.Ticket.objects.filter(user=request.user)
    reviews = models.Review.objects.filter(user=request.user)

    tickets_and_reviews = sorted(
        chain(tickets, reviews),
        key=lambda instance: instance.time_created,
        reverse=True
    )
    paginator = Paginator(tickets_and_reviews, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'all_tickets': tickets,
        'page_obj': page_obj,
    }

    return render(request, 'reviews/flux.html', context=context)

@login_required
def view_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    return render(request, 'reviews/view_ticket.html', {'ticket': ticket})

reviews/templates/reviews/create_review.html
{% extends 'header_footer.html' %}
{% block content %}

<div class="row ">
    <div class="col-md-11 text-center border mx-auto pt-2">
        <p>Vous êtes en train de poster en réponse à</p>
        <div class="post col-md-11 text-center border shadow-sm mx-auto my-4 pb-3">
            <div class="row mt-2">
                <div class="col-md-6">
                    {% if request.user == ticket.user %}
                        <p>Vous avez demandé cette critique</p>
                    {% else %}
                        <p>{{ ticket.user}} a demandé une critique</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <p>{{ ticket.time_created }}</p>
                </div>
            </div>
            <h3>{{ ticket.title }}</h3>
            <p>{{ ticket.description }}</p>
            <img src="{{ ticket.image.url }}" class="img-fluid shadow-lg bg-white rounded">
        </div>
    </div>
</div>
<form action="" method="POST" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-md-11 text-center border mx-auto pt-4 mb-4">
                {{ review_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="col-4 btn btn-block btn-lg btn-success mx-auto mb-4">Publier</button>
        </div>
    </div>
</form>

{% endblock %}

reviews/templates/reviews/create_reviews_ticket.html
{% extends 'header_footer.html' %}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-md-8 text-center border mx-auto pt-4 mb-4">
            <div class="pb-4">
                <h2>Créer une critique</h2>
                {{ ticket_form.as_p }}
            </div>
            <div class="border-top pt-4">
                    {{ review_form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="col-4 btn btn-block btn-lg btn-success mx-auto mb-4">Envoyer</button>
            </div>
        </div>

    </div>
</form>

{% endblock %}

reviews/templates/reviews/flux.html
{% extends 'header_footer.html' %}
{% block content %}

    <div class="row text-center mx-auto" style="width: 150px;">
        <h2>Vos posts</h2>
    </div>

    <div class="grid-container">
    {% for obj in page_obj %}
        {% if obj.title %}
        <div class="post col-md-11 text-center border shadow-sm mx-auto my-4">
            <a href="{% url 'view_ticket' obj.id %}">
                <div class="row mt-2">
                    <div class="col-md-6">
                    {% if request.user == obj.user %}
                        <p>Vous avez demandé cette critique</p>
                    {% else %}
                        <p>{{ obj.user}} a demandé une critique</p>
                    {% endif %}
                    </div>
                    <div class="col-md-6">
                        <p>{{ obj.time_created }}</p>
                    </div>
                </div>
                <h3>Ticket : {{ obj.title }}</h3>
                <p>{{ obj.description }}</p>
                <img src="{{ obj.image.url }}" class="img-fluid shadow-lg bg-white rounded mb-4">
                <div class="row">
                    {% if obj.review_set.all.count == 0 %}
                        <div class="post col-md-4 text-center mx-auto mb-4">
                            <a class="nav-link" href="{% url 'review_create' obj.id %}">
                                <button type="button" class="btn btn-block btn-lg btn-outline-success mb-1">Créer une critique</button>
                            </a>  
                        </div>
                    {% endif %}

                    <div class="post col-md-4 text-center mx-auto mb-4">
                        <a class="nav-link" href="{% url 'edit_ticket' obj.id %}">
                            <button type="button" class="btn btn-block btn-lg btn-outline-warning mb-1">Modifier le billet</button>
                        </a> 
                    </div>
                    <div class="post col-md-4 text-center mx-auto mb-4 mt-2">
                        <form method="post" action="{% url 'delete_ticket' obj.id %}">
                            {{ delete_ticket }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-block btn-lg btn-outline-danger mb-1">Supprimer le billet</button>
                        </form>
                    </div> 
                </div>
            </a>
        </div>
        {% endif %}

        {% if obj.ticket %}

        <a href="{% url 'view_review' obj.ticket.id obj.id %}">
        <div class="post col-md-11 text-center border shadow-sm mx-auto mt-4 mb-8">
            <div class="row mt-2">
                <div class="col-md-6">
                    {% if request.user == obj.user %}
                        <p>Vous avez publié cette critique</p>
                    {% else %}
                        <p>{{ obj.user}} a publié cette critique</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <p>{{ obj.time_created }}</p>
                </div>
            </div>
            <h3>Review : {{ obj.headline }}</h3>
            {% with ''|center:obj.rating as Mylist1 %}
                {% for i in Mylist1 %}
                <i class="fas fa-star"></i>
                    {% if forloop.counter == obj.rating %}                            
                        {% with ''|center:5 as Mylist2 %}
                            {% for j in Mylist2 %}
                                {% if forloop.parentloop.counter|add:forloop.counter == 1 %}                            
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 2 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 3 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 4 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 5 %}
                                    <i class="far fa-star"></i>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            {% endwith %}
            {% if obj.rating == 0 %} 
                {% with ''|center:5 as Mylist3 %}
                    {% for k in Mylist3 %}
                        <i class="far fa-star"></i>
                    {% endfor %}
                {% endwith %}
            {% endif %}
            <p>{{ obj.body }}</p>
       
            <div class="post col-md-11 text-center border shadow-sm mx-auto px-4 py-4">
                    <h3>Ticket - {% if request.user == obj.ticket.user %} Vous {% else %} {{ obj.ticket.user }} {% endif %}</h3>
                    <p>{{ obj.ticket.title }}</p>
                    <p>{{ obj.ticket.description }}</p>
                    <img src="{{ obj.ticket.image.url }}" class="img-fluid shadow-lg bg-white rounded">     
            </div>
            </a>
            
            <div class="row my-4">
                {% if request.user == obj.user %}
                    <div class="post col-md-4 text-center mx-auto">
                        <a class="nav-link" href="{% url 'edit_review' obj.ticket.id obj.id %}">
                            <button type="button" class="btn btn-block btn-lg btn-outline-warning mb-1">Modifier la critique</button>
                        </a>
                    </div>            
                {% endif %}
                <div class="post col-md-4 text-center mx-auto mt-2">
                    <form method="post" action="{% url 'delete_review' obj.id %}">
                        {{ delete_review }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-lg btn-outline-danger mb-1">Supprimer la critique</button>
                    </form>
                </div>
            </div>

        </div>
        {% endif %}
    {% endfor %}
    <div class="row text-center mb-4">
        <div class="col">
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fas fa-fast-backward"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-step-backward"></i></a>
                {% endif %}
            
                <span>
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.

                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-step-forward"></i></a>
                    
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-fast-forward"></i></a>
                {% endif %}
            </span>
        </div>
    </div>
    {% if not page_obj %}
    <p>Il n'y a pas de tickets</p>
    {% endif %}
    </div>
{% endblock %}

reviews/templates/reviews/home.html
{% extends 'header_footer.html' %}
{% block content %}

    <div class="row text-center">
        <div class="col">  
            <a class="nav-link" href="/reviews/ticket_create">
                <button type="button" class="btn btn-block btn-lg btn-outline-warning">Demander une critique</button>
            </a>
        </div>
        <div class="col">
            <a class="nav-link" href="/reviews/ticket_and_review_create">
                <button type="button" class="btn btn-block btn-lg btn-outline-success">Créer une critique</button>
            </a>
        </div>
    </div>

    <div class="grid-container">
    {% for obj in page_obj %}
        {% if obj.title %}
        <div class="post col-md-11 text-center border shadow-sm mx-auto my-4">
            <a href="{% url 'view_ticket' obj.id %}">
                <div class="row mt-2">
                    <div class="col-md-6">
                        {% if request.user == obj.user %}
                            <p>Vous avez demandé cette critique</p>
                        {% else %}
                            <p>{{ obj.user}} a demandé une critique</p>
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        <p>{{ obj.time_created }}</p>
                    </div>
                </div>
                <h3>Ticket : {{ obj.title }}</h3>
                <p>{{ obj.description }}</p>
                <img src="{{ obj.image.url }}" class="img-fluid shadow-lg bg-white rounded mb-4">
                    {% if obj.review_set.all.count == 0 %}
                    <div class="row justify-content-end mb-4">
                        <div class="post col-md-4 text-center">
                            <a class="nav-link" href="{% url 'review_create' obj.id %}">
                                        <button type="button" class="btn btn-block btn-lg btn-outline-success mb-1">Créer une critique</button>
                            </a> 
                        </div>
                    </div>
                    {% endif %}
            </a>
        </div>
        {% endif %}

        {% if obj.ticket %}

        <a href="{% url 'view_review' obj.ticket.id obj.id %}">
        <div class="post col-md-11 text-center border shadow-sm mx-auto mt-4 mb-8">
        
            <div class="row mt-2">
                <div class="col-md-6">
                    {% if request.user == obj.user %}
                        <p>Vous avez publié cette critique</p>
                    {% else %}
                        <p>{{ obj.user}} a publié cette critique</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <p>{{ obj.time_created }}</p>
                </div>
            </div>
            <h3>{{ obj.headline }}</h3>
            {% with ''|center:obj.rating as Mylist1 %}
                {% for i in Mylist1 %}
                <i class="fas fa-star"></i>
                    {% if forloop.counter == obj.rating %}                            
                        {% with ''|center:5 as Mylist2 %}
                            {% for j in Mylist2 %}
                                {% if forloop.parentloop.counter|add:forloop.counter == 1 %}                            
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 2 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 3 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 4 %}
                                    <i class="far fa-star"></i>
                                {% elif forloop.parentloop.counter|add:forloop.counter == 5 %}
                                    <i class="far fa-star"></i>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            {% endwith %}
            {% if obj.rating == 0 %} 
                {% with ''|center:5 as Mylist3 %}
                    {% for k in Mylist3 %}
                        <i class="far fa-star"></i>
                    {% endfor %}
                {% endwith %}
            {% endif %}
            <p>{{ obj.body }}</p>
        
            <div class="post col-md-11 text-center border shadow-sm mx-auto px-4 py-4 mb-4">
                    <h3>Ticket - {% if request.user == obj.ticket.user %} Vous {% else %} {{ obj.ticket.user }} {% endif %}</h3>
                    <p>{{ obj.ticket.title }}</p>
                    <p>{{ obj.ticket.description }}</p>
                    <img src="{{ obj.ticket.image.url }}" class="img-fluid shadow-lg bg-white rounded">     
            </div>
            </a>
        </div>
        {% endif %}
    {% endfor %}
    <div class="row text-center mb-4">
        <div class="col">
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fas fa-fast-backward"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-step-backward"></i></a>
                {% endif %}
            
                <span>
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.

                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-step-forward"></i></a>
                    
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-fast-forward"></i></a>
                {% endif %}
            </span>
        </div>
    </div>
    {% if not page_obj %}
    <p>Il n'y a pas de tickets</p>
    {% endif %}
    </div>
{% endblock %}

reviews/templates/reviews/view_ticket.html
{% extends 'header_footer.html' %}
{% block content %}
<div class="row ">
    <div class="col-md-11 text-center border mx-auto mb-4">
        <p>{{ ticket.id }}</p>
        <h3>{{ ticket.title }} by {{ ticket.user }}</h3>
        <p>{{ ticket.description }}</p>
        <img src="{{ ticket.image.url }}" class="img-fluid shadow-lg bg-white rounded mb-4">

        <div class="row">
            {% if ticket.review_set.all.count == 0 %}
                <div class="post col-md-4 text-center mx-auto mb-4">
                    <a class="nav-link" href="{% url 'review_create' ticket.id %}">
                        <button type="button" class="btn btn-block btn-lg btn-outline-success mb-1">Créer une critique</button>
                    </a>  
                </div>
            {% endif %}
            {% if request.user == ticket.user %}
            <div class="post col-md-4 text-center mx-auto mb-4">
                <a class="nav-link" href="{% url 'edit_ticket' ticket.id %}">
                    <button type="button" class="btn btn-block btn-lg btn-outline-warning mb-1">Modifier le billet</button>
                </a> 
            </div>
            <div class="post col-md-4 text-center mx-auto mb-4 mt-2">
                <form method="post" action="{% url 'delete_ticket' ticket.id %}">
                    {{ delete_ticket }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-block btn-lg btn-outline-danger mb-1">Supprimer le billet</button>
                </form>
            </div> 
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}