LITReview_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf.urls.static import static
from reviews import views

import reviews.views
import authentication.views

urlpatterns = [
    url(r'^$', reviews.views.home, name='home'),
    url(r'^login/', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True),
        name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', reviews.views.home, name='home'),
    url(r'^signup/$', authentication.views.signup_page, name='signup'),
    url(r'^view_follows$', reviews.views.view_follows, name='view_follows'),
    url(r'^reviews/ticket_create$', reviews.views.ticket_upload, name='ticket_create'),
    url(r'^reviews/ticket_and_review_create$', reviews.views.review_and_ticket_upload, name='review_and_ticket_create'),
    url(r'^reviews/my_posts$', reviews.views.my_posts, name='my_posts'),
    path('delete_follows/<int:follower_id>', reviews.views.delete_follows, name='delete_follows'),
    path('add_follow/', reviews.views.add_follow, name='add_follow'),
    path('reviews/<int:ticket_id>', reviews.views.view_ticket, name='view_ticket'),
    path('reviews/<int:ticket_id>/edit', reviews.views.edit_ticket, name='edit_ticket'),
    path('reviews/<int:ticket_id>/delete_ticket', reviews.views.delete_ticket, name='delete_ticket'),
    path('reviews/<int:ticket_id>/review_create', reviews.views.review_upload, name='review_create'),
    path('reviews/<int:ticket_id>/<int:review_id>', reviews.views.view_review, name='view_review'),
    path('reviews/<int:ticket_id>/<int:review_id>/edit', reviews.views.edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete_review', reviews.views.delete_review, name='delete_review'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.conf.urls import url

from . import views # import views so we can use them in urls.
import reviews.views

urlpatterns = [
    # url(r'^$', views.index), # "/store" will call the method "index" in "views.py"
    # url(r'^$', views.listing, name='listing'),
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^search/$', views.search, name='search'),
]

reviews/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models

from PIL import Image


class Ticket(models.Model):
    IMAGE_MAX_SIZE = (900, 900)
    
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def resize_image(self):
        print("self")
        print(self)
        print(self.image)
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, unique=True, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ['user', 'followed_user']

templates/header_footer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    {% load static %}
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
    >
    <title>LITReview</title>
    <style>
      #id_rating li {
        list-style-type: none;
        display: inline;
        text-align: center;
        margin: 0 10px 0 0;   
      }
      a {
        text-decoration: none;
        color: black;
      }
    </style>
  </head>
  <body>
    
    <!-- Header -->
    <div class="bg-dark">
      <div class="container">
        <div class="row justify-content-around">
          <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="col navbar-brand" href="/home">
              <img src="{% static 'reviews/images/logo_litreviews.PNG' %}" width="50" height="50" alt="Info Logo" />
              LITReview
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="col-11">
              {% if user.is_authenticated %}
              <div id="navbarContent" class="collapse navbar-collapse">
                <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="/home">Flux</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'my_posts' %}">Posts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'view_follows' %}">Abonnements</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
                  </li>
                </ul>
              </div>
              {% endif %}
            </div>
          </nav>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col">
          <div class="jumbotron text-center">
            <h1>Bienvenue sur LITReview!</h1>
          </div>
        </div>
      </div>
      
      {% block content %}{% endblock content %}

      <div class="bg-dark">
        <div class="container static-bottom">
          <div class="row">
            <div class="col">
              <ul class="list-inline text-center mt-4">
                <li class="list-inline-item"><a href="#">À propos</a></li>
                <li class="list-inline-item">&middot;</li>
                <li class="list-inline-item"><a href="#">Vie privée</a></li>
                <li class="list-inline-item">&middot;</li>
                <li class="list-inline-item"><a href="#">Conditions d'utilisations</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-dark">
      <div class="container">
        <div class="row">
        </div>
      </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://kit.fontawesome.com/65238440ca.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>